# Generated by Django 4.2.2 on 2023-06-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='universe',
            field=models.CharField(choices=[('Star Wars', 'Star Wars'), ('Residen Evil', 'Resident Evil'), ('LOTR', 'Lord Of The Rings'), ('Other', 'Other')]),
        ),
    ]
