# Generated by Django 4.2.2 on 2023-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_universe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='universe',
            field=models.CharField(choices=[('Star Wars', 'Star Wars'), ('Resident Evil', 'Resident Evil'), ('LOTR', 'Lord Of The Rings'), ('Other', 'Other')]),
        ),
    ]
