# Generated by Django 4.2.2 on 2023-06-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_owner_userproductrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
